const fs = require('fs');
const path = require('path');
const config = require('./tools-config.cjs');

const templateContent = fs.readFileSync('./template.html', 'utf8');

const outputDir = './tools';
if (!fs.existsSync(outputDir)){
    fs.mkdirSync(outputDir, { recursive: true });
}

console.log("🚀 Programmatic SEO Aggressive Engine Execution Started...");

Object.keys(config).forEach(slugKey => {
    const tool = config[slugKey];
    let html = templateContent;

    // Determine tool-specific FAQs dynamically
    const toolNameLower = tool.name.toLowerCase();
    
    let overridenFaqs = null;
    let overridenFields = null;
    
    if (toolNameLower.includes('menu') || toolNameLower.includes('restaurant') || toolNameLower.includes('allergen') || toolNameLower.includes('waiter') || toolNameLower.includes('table ordering') || toolNameLower.includes('fssai')) {
        // Restaurant Menu QR Tool
        overridenFaqs = [
            { "q": "Does the menu QR code expire?", "a": "No, all static QR codes created on EzQR are permanent. The data is hard-coded into the pattern itself, so it never expires." },
            { "q": "Can I update my menu later?", "a": "Yes! Since the QR code links directly to your public menu URL or PDF link, you can easily update the menu document on your own website, Google Drive, or hosting server without needing to change or reprint the physical QR code." },
            { "q": "Will the QR work on iPhone and Android?", "a": "Yes, the patterns generated by EzQR are fully universal and can be scanned natively by both iOS (iPhone) and Android OS cameras." },
            { "q": "What size should I print on table tents?", "a": "For standard table tents and stickers, we recommend a minimum printing size of 2x2 inches (5x5 cm) to ensure effortless, quick scanning under restaurant lighting." },
            { "q": "Can customers scan without installing an app?", "a": "Absolutely. Customers do not need any custom app; they simply point their native camera at the QR code and tap the instant link." },
            { "q": "Can I use the QR on restaurant flyers?", "a": "Yes, you can download the high-resolution vector and print it on takeaway flyers, brochures, mailers, or receipts." }
        ];
        overridenFields = [
            { "id": "in-restaurant-name", "label": "Restaurant Name / Outlet", "type": "text", "placeholder": "e.g., Bella Vista Pizzeria", "guard": "menu-restaurant" },
            { "id": "in-menu-url", "label": "Menu URL / PDF Document Link", "type": "url", "placeholder": "https://myrestaurant.com/menu.pdf", "guard": "menu-url" },
            { "id": "in-menu-table", "label": "Table / Cabin ID (Optional)", "type": "text", "placeholder": "e.g. Table 04", "guard": "menu-table" }
        ];
    } else if (toolNameLower.includes('wedding') || toolNameLower.includes('rsvp') || toolNameLower.includes('matrimony') || toolNameLower.includes('event') || toolNameLower.includes('webinar') || toolNameLower.includes('ticket') || toolNameLower.includes('itinerary') || toolNameLower.includes('charity') || toolNameLower.includes('donation')) {
        // Wedding / Events RSVP QR Tool
        overridenFaqs = [
            { "q": "Can I print this QR on wedding cards?", "a": "Yes! Placing a clean RSVP QR code directly onto your physical wedding invitations or digital e-cards allows guests to easily scan and reply in real time." },
            { "q": "Will the QR work after the wedding date?", "a": "Yes, the QR pattern remains permanently valid, serving as an everlasting digital legacy for your friends to download memories or see wedding schedules." },
            { "q": "What is the best QR size for invitations?", "a": "For elegant invitation cards, print the QR code at least 1.2x1.2 inches (3x3 cm). Maintaining a clean breathing space of negative margins around the code ensures easy scanning." },
            { "q": "Can guests scan from WhatsApp images?", "a": "Yes! Most modern messaging apps allow users to long-press any received image containing a QR code to read its content natively." },
            { "q": "Can I use custom wedding colors?", "a": "Definitely. You can utilize our custom Color pickers on the homepage to match your wedding invite pastel palettes." }
        ];
        overridenFields = [
            { "id": "in-bride-name", "label": "Bride's Name", "type": "text", "placeholder": "e.g., Deepika", "guard": "wedding" },
            { "id": "in-groom-name", "label": "Groom's Name", "type": "text", "placeholder": "e.g., Ranveer", "guard": "wedding" },
            { "id": "in-rsvp-url", "label": "RSVP / Registry Target Link", "type": "url", "placeholder": "https://rsvp.ourwedding.com", "guard": "wedding-rsvp" },
            { "id": "in-wedding-date", "label": "Wedding / Event Date", "type": "date", "placeholder": "Select celebration date", "guard": "wedding-date" }
        ];
    } else if (toolNameLower.includes('resume') || toolNameLower.includes('cv') || toolNameLower.includes('portfolio') || toolNameLower.includes('github') || toolNameLower.includes('behance')) {
        // Resume QR Tool
        overridenFaqs = [
            { "q": "Can recruiters scan the QR from a printed resume?", "a": "Yes! Recruiters can instantly scan your physical resume to view your live portfolio, GitHub projects, or dynamic case studies." },
            { "q": "Should I place the QR at the top or bottom of my resume?", "a": "We recommend placing a clean, modern QR code in the top-right header parallel to your contact details or centered at the bottom of the CV." },
            { "q": "Can I link my LinkedIn profile?", "a": "Absolutely. You can paste your primary LinkedIn URL, personal portfolio, or Linktree direct addresses to bridge the gap between paper and screen." },
            { "q": "What is the ideal QR size for A4 resumes?", "a": "The ideal size for A4 resumes is 1x1 inch (2.5x2.5 cm). This ensures high print legibility without occupying too much visual resume estate." },
            { "q": "Will ATS systems be affected?", "a": "No. Applicant Tracking Systems (ATS) examine plain text fields. Having an image-based QR block inside your layout will not disturb standard parsing as long as it has wrapping margins." }
        ];
        overridenFields = [
            { "id": "in-resume-url", "label": "Resume File Link (Google Drive / PDF / Dropbox)", "type": "url", "placeholder": "https://drive.google.com/file/.../view", "guard": "resume" },
            { "id": "in-portfolio-url", "label": "Portfolio Web Address", "type": "url", "placeholder": "https://yourportfolio.com", "guard": "resume-portfolio" },
            { "id": "in-linkedin-url", "label": "LinkedIn Profile Address", "type": "url", "placeholder": "https://linkedin.com/in/username", "guard": "resume-linkedin" }
        ];
    } else if (toolNameLower.includes('airbnb') || toolNameLower.includes('welcome guide') || toolNameLower.includes('guest network') || toolNameLower.includes('hotel') || toolNameLower.includes('room wifi') || toolNameLower.includes('concierge') || toolNameLower.includes('smart home')) {
        // Airbnb / Hotel Welcome Guide QR Tool
        overridenFaqs = [
            { "q": "Can guests scan without downloading an app?", "a": "Yes! Guests scan the code natively on their camera app which takes them to your house guide, digital WiFi link, or welcome PDF instantly." },
            { "q": "Can I link house rules?", "a": "Yes, you can generate QR codes for digital House Rules, local recommend tourist trip maps, check-out checklists, or instruction videos." },
            { "q": "Can I add WiFi instructions?", "a": "Yes! You can put your custom high-speed WiFi credentials inside a specific scan-to-connect code to bypass manual passwords." },
            { "q": "What is the best location to place the QR?", "a": "Place the printed welcome QR inside front entry frames, laminated kitchen leaflets, or bedside tables." },
            { "q": "Can I print it on welcome cards?", "a": "Yes, downloading our high-resolution transparent files guarantees that whether you print on wood, plastic, or acrylic cards, scanning remains pixel-perfect." }
        ];
        overridenFields = [
            { "id": "in-airbnb-name", "label": "Property / Room Name", "type": "text", "placeholder": "e.g., Sunshine Villa Room 3B", "guard": "airbnb-name" },
            { "id": "in-airbnb-guide", "label": "Welcome Guide Website / Drive Link", "type": "url", "placeholder": "https://host.com/welcome-to-sunshine", "guard": "airbnb-guide" },
            { "id": "in-airbnb-wifi", "label": "WiFi Connection Details", "type": "text", "placeholder": "e.g. SSID: Sunshine_5G / Secret: sunvilla2026", "guard": "airbnb-wifi" }
        ];
    } else if (toolNameLower.includes('upi') || toolNameLower.includes('pay') || toolNameLower.includes('wallet') || toolNameLower.includes('crypto' ) || toolNameLower.includes('solana') || toolNameLower.includes('usdt') || toolNameLower.includes('binance') || toolNameLower.includes('token') || toolNameLower.includes('address')) {
        // UPI / Payments QR
        overridenFaqs = [
            { "q": "Does EzQR store my UPI details?", "a": "Never. EzQR.io is a strictly offline-first client-side web application. Your account numbers, VPA strings, and payment amounts are security-nested in your local browser." },
            { "q": "Can customers pay using PhonePe, GPay and Paytm?", "a": "Yes! Standard BHIM UPI schemes embedded in the QR are natively recognizable by Google Pay, PhonePe, Paytm, BHIM, Cred, and Amazon Pay." },
            { "q": "Can I print the QR in my shop?", "a": "Absolutely! Download the high-resolution PNG, print it out, and laminate it for your billing counter or cash registers." },
            { "q": "Can I create a fixed-amount payment QR?", "a": "Yes! If you input an amount into the form, scanning the QR will auto-populate that exact amount in the customer's UPI app." },
            { "q": "Is the QR valid forever?", "a": "Yes. As long as your active UPI ID / VPA remains registered and active with your linked bank account, the printed QR code will work permanently." }
        ];
        if (toolNameLower.includes('upi')) {
            overridenFields = [
                { "id": "in-upi-vpa", "label": "Your UPI ID / VPA Address", "type": "text", "placeholder": "e.g., suicidex@okaxis or 9876543210@paytm", "guard": "upi-vpa" },
                { "id": "in-upi-name", "label": "Merchant / Name", "type": "text", "placeholder": "e.g., Suvash Shastri", "guard": "upi-name" },
                { "id": "in-upi-amt", "label": "Transaction Amount (Optional)", "type": "number", "placeholder": "e.g., 500 (leave blank to let customer type)", "guard": "upi-amt" }
            ];
        } else {
            overridenFields = [
                { "id": "in-crypto-addr", "label": "Crypto Wallet Destination Address", "type": "text", "placeholder": "Paste Bitcoin / Solana / USDT Address", "guard": "crypto" },
                { "id": "in-crypto-amt", "label": "Amount Value (Optional)", "type": "number", "placeholder": "e.g., 0.15", "guard": "crypto-amt" }
            ];
        }
    } else if (toolNameLower.includes('wifi') || toolNameLower.includes('ssid')) {
        // WiFi QR Tool
        overridenFaqs = [
            { "q": "Can guests connect without typing the password?", "a": "Yes, scanning the standard WiFi QR protocol prompts a direct 'Join Network' button on Android and iOS, allowing users to connect with a single tap." },
            { "q": "Does the QR reveal my password?", "a": "The credentials (SSID and password) are encoded directly inside the pattern. While camera apps read the security parameters automatically to connect, the raw password is not visible in plain text on the printed design itself." },
            { "q": "Will it work on iPhone?", "a": "Yes! iPhones running iOS 11 and above have native, built-in WiFi QR recognition. Simply aim the camera, tap the 'Join' notification banner, and connect." },
            { "q": "Will it work on Android?", "a": "Yes. Android devices have natively integrated support for the standard WIFI:S: protocol. It works flawlessly across all Android models." },
            { "q": "Can I print the QR near my router?", "a": "Yes! Printing and sticking a clean WiFi QR code on your router or living room wall is highly recommended for smart homes, Airbnb hosts, and office workspaces." }
        ];
        overridenFields = [
            { "id": "in-wifi-ssid", "label": "WiFi Network Name (SSID)", "type": "text", "placeholder": "e.g., SweetHome_5G", "guard": "wifi" },
            { "id": "in-wifi-pass", "label": "WiFi Security Password", "type": "text", "placeholder": "Enter network password", "guard": "wifi-pass" },
            { "id": "in-wifi-sec", "label": "Encryption Type", "type": "select", "placeholder": "WPA", "guard": "wifi-sec" }
        ];
    } else if (toolNameLower.includes('vcard') || toolNameLower.includes('business card') || toolNameLower.includes('contact') || toolNameLower.includes('profile')) {
        // Business Card QR Tool
        overridenFaqs = [
            { "q": "Can contacts be saved instantly?", "a": "Yes. The QR code contains an industry-standard vCard (.vcf) payload. When scanned, it automatically prompts the recipient's phone to open their contacts app with your name, phone, email, and social links pre-filled." },
            { "q": "Can I add multiple phone numbers?", "a": "Yes! Our forms support full vCard fields, allowing you to include a primary work number, mobile line, organization website, and email address." },
            { "q": "Can I add social profiles?", "a": "Yes, you can include your primary web URLs, company profiles, or LinkedIn addresses in the website field." },
            { "q": "Can I print on business cards?", "a": "Yes, the generated high-contrast code can be directly imported into professional design programs like Canva, Photoshop, or Adobe Illustrator for custom business card layouts." },
            { "q": "Will it work offline after printing?", "a": "Absolutely! Since the standard contact information is stored directly inside the physical black-and-white matrix dots of the QR code itself, it works even when both devices are completely offline!" }
        ];
        overridenFields = [
            { "id": "in-contact-name", "label": "Full Name", "type": "text", "placeholder": "e.g., Suvash Astrologer", "guard": "contact" },
            { "id": "in-contact-phone", "label": "Mobile Phone Number", "type": "tel", "placeholder": "e.g., +91 9876543210", "guard": "contact" },
            { "id": "in-contact-email", "label": "Professional Email Address", "type": "email", "placeholder": "e.g., suvash.astrology@gmail.com", "guard": "contact" },
            { "id": "in-contact-web", "label": "Business Domain / Website", "type": "url", "placeholder": "https://ezqr.io", "guard": "contact-web" }
        ];
    } else if (toolNameLower.includes('brochure') || toolNameLower.includes('tour') || toolNameLower.includes('real estate') || toolNameLower.includes('agent') || toolNameLower.includes('property') || toolNameLower.includes('building') || toolNameLower.includes('address') || toolNameLower.includes('maps')) {
        // Property Brochure QR Tool
        overridenFaqs = [
            { "q": "Can I link a PDF brochure?", "a": "Yes, upload your property brochure or floor plan to a file host (such as Google Drive, Dropbox, or your company website) and paste the public link into the form to generate the code." },
            { "q": "Can buyers scan from printed banners?", "a": "Yes, our high-resolution files can be scaled to massive sizes, making them perfect for large yard signs, property gates, road-side billboards, and window stickers." },
            { "q": "Can I add virtual tour links?", "a": "Yes, you can easily link directly to 360-degree virtual property tours, YouTube walkthroughs, or physical coordinate drops on Google Maps." },
            { "q": "What QR size works on property signs?", "a": "For standard roadside yard signs (approx. 18x24 inches), ensure your QR code is at least 4x4 inches to allow quick scanning by passing drivers or pedestrians." },
            { "q": "Can I use this on newspaper ads?", "a": "Yes, placing a crisp, high-contrast QR code on print media such as local magazines or classified ads redirects offline buyers directly to your digital listings." }
        ];
        overridenFields = [
            { "id": "in-property-name", "label": "Property Name / Venture", "type": "text", "placeholder": "e.g., Green Valley Meadows", "guard": "property" },
            { "id": "in-property-pdf", "label": "Brochure Link / Catalog PDF", "type": "url", "placeholder": "https://example.com/valley-brochure.pdf", "guard": "property-pdf" },
            { "id": "in-property-phone", "label": "Contact Phone / Helpline", "type": "tel", "placeholder": "e.g., +91 9999999999", "guard": "property-phone" }
        ];
    } else {
        // Fallback or general tool specific FAQ
        overridenFaqs = [
            { "q": "Will my custom " + tool.name + " code ever expire?", "a": "No, all static QR codes created with EzQR are standard-compliant and permanent. The payload data is hardcoded into the graphic elements, so it never expires." },
            { "q": "Is scanning completely free and unlimited?", "a": "Yes! Scanning the QR code is 100% free with absolutely no scan ceilings, download caps, or usage limitations ever." },
            { "q": "Can I edit the destination link in the future?", "a": "Static QR codes store the literal data points permanently. To edit, you can generate a new code for free instantly, or use an existing domain redirect service at your target link." },
            { "q": "Will this QR scan easily on high-resolution screens?", "a": "Yes. Our engine uses crisp styling elements optimized for maximum readability to guarantee responsive scans on any device or paper medium." }
        ];
    }
    
    if (overridenFaqs) {
        tool.faqs = overridenFaqs;
    }

    if (overridenFields) {
        tool.fields = overridenFields;
    }

    // 1. Structural Metadata Interpolation
    html = html.replace(/{{TOOL_META_TITLE}}/g, tool.metaTitle);
    html = html.replace(/{{TOOL_META_DESC}}/g, tool.metaDesc);
    html = html.replace(/{{TOOL_H1_NAME}}/g, tool.h1Title);
    html = html.replace(/{{TOOL_SHORT_NAME}}/g, tool.shortName);

    // 2. Neon Badges Injection Loop
    let badgesHtml = tool.badges.map(b => `<span class="badge-node">${b}</span>`).join('');
    html = html.replace(/{{TOOL_BADGES}}/g, badgesHtml);

    // 3. Dynamic Form Fields Parser
    let fieldsHtml = tool.fields.map(f => {
        if (f.type === 'select') {
            return `<div style="margin-bottom:12px;">
              <label class="flabel">${f.label}</label>
              <select class="fi qi" id="${f.id}" data-guard="${f.guard}" style="width:100%; padding:10px 12px; height: 42px; background:var(--s2); border:1px solid var(--bd); border-radius:10px; color:var(--tx); outline:none; font-size:13px; font-weight: 500; appearance: none; cursor:pointer;">
                <option value="WPA">WPA/WPA2 Secured</option>
                <option value="WEP">WEP Encryption</option>
                <option value="nopass">Open/Unsecured</option>
              </select>
            </div>`;
        }
        return `<div><label class="flabel">${f.label}</label><input class="fi qi" type="${f.type}" id="${f.id}" placeholder="${f.placeholder}" data-guard="${f.guard}"></div>`;
    }).join('');
    html = html.replace(/{{DYNAMIC_FORM_FIELDS}}/g, fieldsHtml);

    // 4. Specifications Tables Matrix Builder
    let specsHtml = Object.keys(tool.specs).map(key => {
        return `<tr><td>${key}</td><td>${tool.specs[key]}</td></tr>`;
    }).join('');
    html = html.replace(/{{TOOL_SPECS_TABLE}}/g, specsHtml);

    // 5. Documentation & Long-Tail Body Content Injections
    html = html.replace(/{{TOOL_HOW_TO_USE}}/g, tool.howToUse);
    html = html.replace(/{{TOOL_HOW_IT_WORKS}}/g, tool.howItWorks);

    // 6. Q&A FAQ Template Blocks Render
    let faqHtml = tool.faqs.map(f => {
        return `<div class="faq-node"><div class="faq-q">Q: ${f.q}</div><div class="faq-a">A: ${f.a}</div></div>`;
    }).join('');
    html = html.replace(/{{TOOL_FAQ_BLOCK}}/g, faqHtml);

    // 7. Context Cross-Linking Pills Generator
    let relatedHtml = tool.related.map(r => {
        const cleanSlug = r.path.replace(/^\//, '');
        return `<a class="pill-route" href="../${cleanSlug}/index.html">${r.name}</a>`;
    }).join('');
    html = html.replace(/{{TOOL_RELATED_PILLS}}/g, relatedHtml);

    // 8. Google Rich Snippet JSON-LD Integration
    let schemaObj = {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://ezqr.io" },
            { "@type": "ListItem", "position": 2, "name": "Tools", "item": "https://ezqr.io/#directory" },
            { "@type": "ListItem", "position": 3, "name": tool.shortName }
          ]
        },
        {
          "@type": "FAQPage",
          "mainEntity": tool.faqs.map(f => ({
            "@type": "Question",
            "name": f.q,
            "acceptedAnswer": { "@type": "Answer", "text": f.a }
          }))
        }
      ]
    };
    let schemaScript = `<script type="application/ld+json">${JSON.stringify(schemaObj)}<\/script>`;
    html = html.replace(/{{GOOGLE_JSON_LD_SCHEMA}}/g, schemaScript);

    // 9. Physical Directory Structural Folder Dump
    const toolFolder = `./tools/${slugKey}`;
    if (!fs.existsSync(toolFolder)){
        fs.mkdirSync(toolFolder, { recursive: true });
    }
    
    fs.writeFileSync(`${toolFolder}/index.html`, html, 'utf8');
});

console.log("🎯 Pure Programmatic Framework Compilation Complete! 100% Locked.");
